### PR TITLE
website overhaul - part 1

### PR DESCRIPTION
**Pull request by PeerHerholz**
This PR starts the website overhaul, proposing a new outline and respective content. In more detail, the website will be changed from a workshop-specific website to a general project website that will entail the workshop information among other central aspects of the project. The following main changes were/will be implemented:
- [x] the logo was changed to reflect the new scope of the website
- [x] the header was adapted to include sections for a general project overview, the scope & approach, the workshops & contact information
- [x] drafts of respective content were added
- [x] instead of having everything on one page, sections now lead to subpages  
- [x] adapt formatting and style
- [x] workshop-specific pages

### CODE REVIEW

**Review by anibalsolon — APPROVED** [review]
🎉 🎉 🎉  Great work!

**Comment by PeerHerholz** [comment]
Hi @francopestilli,

does this look ok re a first draft of the new outline? Happy to adapt content and organization of course!
If so, we could merge it and @anibalsolon and I would then work out the formatting and style of the new layout.

It would be cool to get your thoughts on this.

Cheers, Peer

**Comment by anibalsolon** [comment]
hey @PeerHerholz could you enable the website in your fork? this way we could check it online, without requiring to build it locally

**Comment by anibalsolon** [comment]
Ah, you are the best @PeerHerholz , thank you!

**Comment by PeerHerholz** [comment]
Hi @anibalsolon,

I wanted to ask if you maybe have time in the coming days to have a look at the styling/formatting?

Best, Peer

**Comment by anibalsolon** [comment]
hey @PeerHerholz !! I'm sorry, never got back to you- how is your day tomorrow for some styling? 💅🏻

**Comment by PeerHerholz** [comment]
Hi @anibalsolon,

no worries. Would tomorrow 8 AM CT/3 PM CET work?

**Comment by anibalsolon** [comment]
yep, let's do it!

**Comment by PeerHerholz** [comment]
Hi @anibalsolon,

thx for the styling/formatting fixes. I added content & graphics respectively. Do you maybe have time this week to chat about the subpages for the `workshop` page?

Thx again, cheers, Peer

**Comment by anibalsolon** [comment]
Yes, Friday 8 AM CT/3 PM CET still good?

**Comment by PeerHerholz** [comment]
Yeah, thx so much!

**Review by francopestilli — APPROVED** [review]

**Pull request merged**
